# fly.toml app configuration file generated for dollar-billowing-field-3251 on 2025-04-15T11:50:40-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dollar-billowing-field-3251'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 8050
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
